---
global:
  writeToFile: false
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: ${INDEXING}
    esServers: [${ES_SERVER}]
    insecureSkipVerify: false
    defaultIndex: ${ES_INDEX}
    type: elastic
  measurements:
    - name: podLatency
      esIndex: ${ES_INDEX}

jobs:
  - name: load-cluster
    jobIterations: ${JOB_ITERATIONS}
    qps: ${QPS}
    burst: ${BURST}
    namespacedIterations: true
    namespace: load-cluster
    cleanup: true
    podWait: false
    waitFor: []
    waitWhenFinished: true
    objects:

      - objectTemplate: client.yml
        replicas: 7
        inputVars:
          image: ${CLIENT_IMAGE}
          podReplicas: 3
          readinessProbe: /ready
          readinessPeriod: 2

      - objectTemplate: postgres-deployment.yml
        replicas: 7
        inputVars:
          image: ${SERVER_IMAGE}

      - objectTemplate: postgres-service.yml
        replicas: 7

      - objectTemplate: configmap.yml
        replicas: 10

      - objectTemplate: secret.yml
        replicas: 10
