apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hostnetwork
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostnetwork
subjects:
- kind: ServiceAccount
  name: http-perf-client
  namespace: http-perf-client
