apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: http-perf-edge-{{.Replica}}
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: http-perf-{{.Replica}}

