apiVersion: v1
kind: Pod
metadata:
  name: http-client
spec:
  nodeSelector: {{.nodeSelector}}
  containers:
  - image: quay.io/openshift-scale/http-stress
    name: mb
  restartPolicy: Always
  hostNetwork: true
  securityContext:
    sysctls:
    - name: net.ipv4.ip_local_port_range
      value: "1024 65535"
