apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client-{{.Replica}}
spec:
  selector:
    matchLabels:
      app: http-client-{{.Replica}}
  template:
    metadata:
      labels:
        app: http-client-{{.Replica}}
    spec:
      serviceAccountName: http-perf-client
      tolerations:
        - key: role
          value: workload
          effect: NoSchedule
      nodeSelector: {{.nodeSelector}}
      containers:
      - image: quay.io/openshift-scale/http-stress
        name: mb
      restartPolicy: Always
      hostNetwork: true
