apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: http-perf-passthrough-{{.Replica}}
spec:
  port:
    targetPort: 8443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: http-perf-{{.Replica}}

