kind: Service
apiVersion: v1
metadata:
  name: postgresql-{{.Replica}}
spec:
  selector:
    name: postgres-{{.Replica}}
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  portalIP: ''
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
