---
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: false
    esServers: [http://elastic-elk.apps.rsevilla-ocp45-ovn.perf-testing.devcluster.openshift.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kube-burner
      thresholds:
      - conditionType: Ready
        metric: Avg
        threshold: 4s


jobs:
  - name: kubelet-density
    jobIterations: 50
    qps: 20
    burst: 20
    namespacedIterations: false
    namespace: kubelet-density
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: gcr.io/google_containers/pause-amd64:3.0
