kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-configmap-{{.Replica}}
spec:
  template:
    metadata:
      labels:
        app: client-configmap-{{.Replica}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: perfapp
        image: {{.image}}
        readinessProbe:
          httpGet:
            path: {{.readinessProbe}}
            port: 8080
          periodSeconds: {{.readinessPeriod}}
          failureThreshold: 3
          timeoutSeconds: 30
          initialDelaySeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: client-{{.Replica}}
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: client-{{.Replica}}
              key: password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: client-{{.Replica}}
              key: database
        - name: POSTGRESQL_HOSTNAME
          value: postgres-configmap-{{.Replica}}
        - name: POSTGRESQL_PORT
          value: '5432'
        - name: POSTGRESQL_RETRY_INTERVAL
          value: '5'
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      app: client-configmap-{{.Replica}}
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate
