---
global:
  writeToFile: false
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: true
    esServers: [https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443]
    insecureSkipVerify: false
    defaultIndex: ripsaw-kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: ripsaw-kube-burner

jobs:
  - name: load-cluster
    jobIterations: 
    qps: 20
    burst: 20
    namespacedIterations: true
    namespace: load-cluster
    cleanup: true
    podWait: false
    waitFor: []
    waitWhenFinished: true
    objects:

      - objectTemplate: client.yml
        replicas: 5
        inputVars:
          image: quay.io/rsevilla/perfapp:latest
          podReplicas: 5
          readinessProbe: /ready
          readinessPeriod: 2

      - objectTemplate: postgres-deployment.yml
        replicas: 5
        inputVars:
          image: registry.redhat.io/rhscl/postgresql-10-rhel7:latest

      - objectTemplate: postgres-service.yml
        replicas: 5

      - objectTemplate: postgres-networkpolicy.yml
        replicas: 5

      - objectTemplate: configmap.yml
        replicas: 10

      - objectTemplate: secret.yml
        replicas: 10
