kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: postgres-secret-{{.Replica}}
spec:
  podSelector:
    matchLabels:
      app: postgres-secret-{{.Replica}}
  ingress:
  - ports:
    - port: 5432
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: client-secret-{{.Replica}}
