kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-configmap-{{.Replica}}
spec:
  template:
    metadata:
      labels:
        app: postgres-configmap-{{.Replica}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: postgresql
        image: {{.image}}
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: client-{{.Replica}}
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: client-{{.Replica}}
              key: password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: client-{{.Replica}}
              key: database
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: postgres-configmap-{{.Replica}}
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate
