{
 "title": "Kube-burner report",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "label": "UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\"}"
   },
   {
    "name": "master",
    "label": "Master nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\",  \"query\": \"uuid.keyword: $uuid\", \"query\": \"metricName.keyword: nodeRoles\",  \"query\": \"labels.role.keyword: master\"}"
   },
   {
    "name": "worker",
    "label": "Worker nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\",  \"query\": \"uuid.keyword: $uuid\", \"query\": \"metricName.keyword: nodeRoles\",  \"query\": \"labels.role.keyword: worker\"}"
   },
   {
    "name": "infra",
    "label": "Infra nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\",  \"query\": \"uuid.keyword: $uuid\", \"query\": \"metricName.keyword: nodeRoles\",  \"query\": \"labels.role.keyword: infra\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.namespace.keyword\",  \"query\": \"uuid.keyword: $uuid\", \"query\": \"labels.namespace.keyword: /openshift-.*/\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Kubelet & CRI-O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Kubelet process CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: top10KubeletCPU",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 10 Kubelet process memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: top10KubeletMemory",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 10 CRI-O process CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: top10CrioCPU",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 10 CRI-O process memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:134",
         "fake": true,
         "field": "labels.node.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:61",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:59",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: top10CrioMemory",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra: $infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "infra",
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 CPU usage $infra",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"podCPU\" AND labels.node.keyword: $infra AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 memory usage $infra",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"podMemory\" AND labels.node.keyword: $infra AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $worker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $worker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryAvailable\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      },
      {
       "alias": "cached+buffers",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryCached+nodeMemoryBuffers\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      },
      {
       "alias": "available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Network bytes $worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "txNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1174",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"txNetworkBytes\" AND labels.instance.keyword: \"$infra\"",
       "timeField": "timestamp"
      },
      {
       "alias": "rxNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1215",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND  metricName: \"rxNetworkBytes\" AND labels.instance.keyword: \"$infra\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Disk $worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Written bytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:554",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"nodeDiskWrittenBytes\" AND labels.instance.keyword: \"$infra\"",
       "timeField": "timestamp"
      },
      {
       "alias": "Read bytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:571",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND  metricName: \"nodeDiskReadBytes\" AND labels.instance.keyword: \"$infra\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Conntrack entries $worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Conntrack entries",
       "bucketAggs": [
        {
         "$$hashKey": "object:1885",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1883",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeConntrackEntries\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Dropped packets $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "txDroppedPackets - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1751",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1370",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1368",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"txDroppedPackets\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      },
      {
       "alias": "rxDroppedPackets - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1768",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1594",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1592",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"rxDroppedPackets\" AND labels.instance.keyword: $infra",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker: $worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "worker",
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 CPU usage $worker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"podCPU\" AND labels.node.keyword: $worker AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 memory usage $worker",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"podMemory\" AND labels.node.keyword: $worker AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU\" AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryAvailable\" AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      },
      {
       "alias": "cached+buffers",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryCached+nodeMemoryBuffers\" AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      },
      {
       "alias": "active",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive\" AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Network bytes $worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "txNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1174",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"txNetworkBytes\" AND labels.instance.keyword: \"$worker\"",
       "timeField": "timestamp"
      },
      {
       "alias": "rxNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1215",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"rxNetworkBytes\" AND labels.instance.keyword: \"$worker\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Disk $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Written bytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:554",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"nodeDiskWrittenBytes\" AND labels.instance.keyword: \"$worker\"",
       "timeField": "timestamp"
      },
      {
       "alias": "Read bytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:571",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND  metricName: \"nodeDiskReadBytes\" AND labels.instance.keyword: \"$worker\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Conntrack entries $worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Conntrack entries",
       "bucketAggs": [
        {
         "$$hashKey": "object:1885",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1883",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeConntrackEntries\" AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Dropped packets $worker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "txDroppedPackets - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1751",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1370",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1368",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: txDroppedPackets AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      },
      {
       "alias": "rxDroppedPackets - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1768",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1594",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1592",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: rxDroppedPackets AND labels.instance.keyword: $worker",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "etcd 99th fsync latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"99thEtcdDiskWalFsyncDurationSeconds\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "etcd 99th disk commit latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"99thEtcdDiskBackendCommitDurationSeconds\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Node status summary",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.condition.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeStatus\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Pod status summary",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.phase.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"podStatusCount\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Namespaces",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Namespaces",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"namespaceCount\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Deployments",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"deploymentCount\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Secrets and Configmaps",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Secrets",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"secretCount\"",
       "timeField": "timestamp"
      },
      {
       "alias": "ConfigMaps",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"configmapCount\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Master: $master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "master",
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 CPU  usage $master",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"podCPU\" AND labels.node.keyword: $master AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Top 5 memory usage $master",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"podMemory\" AND labels.node.keyword: $master AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $master",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $master",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryAvailable\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      },
      {
       "alias": "cached+buffers",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryCached+nodeMemoryBuffers\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      },
      {
       "alias": "active",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Network bytes $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "txNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1174",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"txNetworkBytes\" AND labels.instance.keyword: \"$master\"",
       "timeField": "timestamp"
      },
      {
       "alias": "rxNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1215",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND  metricName: \"rxNetworkBytes\" AND labels.instance.keyword: \"$master\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Disk $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Written bytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:554",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"nodeDiskWrittenBytes\" AND labels.instance.keyword: \"$master\"",
       "timeField": "timestamp"
      },
      {
       "alias": "Read bytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:571",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND  metricName: \"nodeDiskReadBytes\" AND labels.instance.keyword: \"$master\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Conntrack entries $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Conntrack entries",
       "bucketAggs": [
        {
         "$$hashKey": "object:1885",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1883",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeConntrackEntries\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Dropped packets $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "txDroppedPackets - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1751",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1370",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1368",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"txDroppedPackets\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      },
      {
       "alias": "rxDroppedPackets - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1768",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1594",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1592",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"rxDroppedPackets\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}